AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket with a user-defined name

Parameters:
  BucketName:
    Type: String
    Description: Name for the new S3 bucket
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9.-]+$'
    ConstraintDescription: Must be a valid S3 bucket name (lowercase letters, numbers, dots, and hyphens only)

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
